
var GAME_LEVELS = [
  ["                                                            xxx                      ",
   "                                                           x!!!x                     ",
   "                                                          xxxvxxx                    ",
   "                                                                                     ",
   "                                 xxxxxxxxxxx                                         ",
   "                                        c                                            ",
   "                                                                                     ",
   "                                                       o               e      o      ",
   "                                                                                     ",
   "                                                     xxxxx      xxxxxxxxxxxxxxxxxxx  ", 
   "                                                 xxxxx                 c          x  ",
   "                                            xxxxxx                                x  ",
   "                        x  b  x             x                                     x  ",
   " xxx            o       x     x     xxxxxxxx                                      x  ",  
   " x                      xxxxxxx                                                   x  ",
   " x       e     xxxx     x     x                                                   x  ",
   " x  @          x  x     x     x                                                   x  ",
   " xxxxxxxxxxxxxxx  x     x     x     xxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxx  ",
   "                  x     x     x     x                    x       x                   ",
   "                  x!!!!!x     x!!!!!x                    x!!!!!!!x                   ",
   "                  x!!!!!x     x!!!!!x                    x!!!!!!!x                   ",
   "                  xxxxxxx     xxxxxxx                    xxxxxxxxx                   ",
   "                                                                                     ",
   "                                                                                     "],
  ["   x                   x                                                                                             x ",
   "   x                   x                                                                                             x ",
   "   x                   x              xxxx                                                                           x ",
   "   x  @                x!!!!!!!!!!!!!!xv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",                                                              
   "   xxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxx!xxxxxxx!xxxxxxxxxxxxx ",                                                                                         
   "   x                   x                   x           xxvxx          c       xxvxx      x    xxvxx   xxvxx          x ",
   "   x  =                x                   x                                             x                           x ",
   "   x                                       x                                             x                           x ",
   "   x                o                      x                                             x                             ",
   "   x     x                                 x                                             x                             ",
   "   x     xxxxxxxxxxxxxxx                                                                 x                             ",
   "   x                          o      o                                                                                 ",
   "   x                              b                                         o                                          ",
   "   x                      xx           xx                                                                              ",
   "   x                      xxxxxxxxxxxxxxx                                                                              ",
   "   x                                                                    xxxxx                                          ",
   "   x                                          o              o      xxxxx   x          o         o        o        o   ",
   "   x   c                          c                  b            xxx       x                                          ",
   "   x                c                      xx                  xxxx         x    e         e         e        e        ",
   "   x                                       xxxxxxxxxxxxxxxxxxxxxx           xxxxx   xxxxxxx   xxxxxxx   xxxxxx   xxxxx ",
   "   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                                       "],
  ["                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ", 
   "                                                                                                                ", 
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "  xxxxxxxxxx!xxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxx ",
   "          xxvxx                xxvxx                xxvxx                               xxvxx                   ",
   "                                                                                                                ",
   "                                                                                                                ", 
   "  x                                                                                                             ", 
   "  x                                                                                                             ",
   "  x                                                                                                             ", 
   "  x                                                                                                             ", 
   "  x                                                                                                             ", 
   "  x                           o                    o                                                     o      ",
   "  x                  b                                                                xxxxxx                    ", 
   "  x      xxx                          xxx                            xxx        xxxxxxx    xxxxxxxxxxxxx        ",
   "  x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxx     xxxx                      xxxxxxxxx",
   "  x                                                 x!!!!!x            x  o  x                               x  ", 
   "  x           o                                     xxx!xxx            x     x                               x  ",
   "  xx                                                   v               x           o                     o   x  ",
   "   xx                                                                  x                                     x  ",
   "    xxx              xxxx                                              x                                     x  ",     
   "      xxx          xxx  xxx                                =           xxxxxxxxxxx   xxxxxxxxx  o  xxxxxxxxxxx  ",
   "        xxxxxxxxxxx       xxx                                                                x     x            ",
   "                           xxx        o                                                      x     x            ",
   "                            xxx                                                              x  o  x            ",
   "                             xxx                                                             x     x            ",
   "                              xxxxxxxxxx                       o                             x     x            ",
   "                                                                                             x  o  x            ",
   "                                                                                             x     x            ",
   "                                            c xxxxxx       xxxxxxx                          !x     x!           ",
   "                                                                          c                !!x  o  x!!          ",
   "                             o         xx                                                !!!!x     x!!!!        ",
   "  x                              xxxxxxx                                               !!!!!!x     x!!!!!!      ",  
   "  x                         xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!x    ",  
   "  x         o           xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!x    ",
   "  x               b    xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!x    ",
   "  x   @             xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                                ",
   "                                                                                                                "],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
